function [sys] = model_3R2C(Roaia,Riwia,Rowoa,Cwalls,Cair)
%This is documentation for FOO.

  A=@(Cwalls,Cair,Roaia,Riwia,Rowoa) [-1/(Cwalls*Roaia)-1/(Cwalls*Riwia) 1/(Cwalls*Riwia); 1/(Cair*Riwia) -1/(Cair*Rowoa)-1/(Cair*Riwia)];
  B=@(Cwalls,Cair,Roaia,Rowoa) [10/Cwalls 1/(Cwalls*Roaia); 0 1/(Cair*Rowoa)];
  Bp=@(Cwalls,Cair,Roaia,Rowoa) [10/Cwalls; 0];
  C=[1 0]; D=[0];

  sys=ss(A(Cwalls,Cair,Roaia,Riwia,Rowoa), ...
         Bp(Cwalls,Cair,Roaia,Rowoa), ...
         C, ...
         D, ...
         'StateName',{'Temp_air','Temp_walls'}, ...
         'OutputName',{'Temp_air'}, ...
        'InputName','Pheat');
end % function
